global.INTERFACE = 'WS2812';
global.NUMBER_LED_OFFSET_BOTTOM = 2;
global.NUMBER_LED_BLUE_TOP = 1;
global.NUMBER_LED_GAP_BETWEEN_ETAGE_AND_TOP = 2;
global.NUMBER_LED_ETAGES = [1, 1, 1];
global.INVERT_ETAGES = false;