global.INTERFACE = 'WS2812';
global.NUMBER_LED_OFFSET_BOTTOM = 7;
global.NUMBER_LED_BLUE_TOP = 19;
global.NUMBER_LED_GAP_BETWEEN_ETAGE_AND_TOP = 21;
global.NUMBER_LED_ETAGES = [19, 19, 19];
global.INVERT_ETAGES = false;